<a href="https://colab.research.google.com/github/bryanlopezb/practicas-machine-learning/blob/main/KNN_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
# Importar las librerías necesarias
import pandas as pd
import numpy as np
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

Los datos de evaluación están en: https://archive.ics.uci.edu/ml/datasets/Car+Evaluation

In [67]:
# Leer los datos e insertar una fila de identificación de atributos
df = pd.read_csv('car.data', names = ['buying', 'maint', 'doors', 'persons' , 'lug_boot', 'safety', 'class'])
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [68]:
# Separar datos y label
X = df[['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']].values
y = df[['class']]
#print(X.head())
print(y.head())

   class
0  unacc
1  unacc
2  unacc
3  unacc
4  unacc


In [69]:
# Convertir lenguaje en datos
encoder = LabelEncoder()
for i in range(len(X[0])):
  X[: , i] = encoder.fit_transform(X[: , i])
print(X)

[[3 3 0 0 2 1]
 [3 3 0 0 2 2]
 [3 3 0 0 2 0]
 ...
 [1 1 3 2 0 1]
 [1 1 3 2 0 2]
 [1 1 3 2 0 0]]


In [70]:
# Convertir lenguaje en datos a través de mapping
y_map = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}

y['class'] = y['class'].map(y_map)
y = np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


In [71]:
# Definir el modelo
knn = neighbors.KNeighborsClassifier(n_neighbors=8, weights='uniform')

In [72]:
# Separar los datos en dos categorías: entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [73]:
# Entrenar el modelo
knn.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [74]:
#Predicciones y prueda
prediction = knn.predict(X_test)

accuracy = metrics.accuracy_score(y_test, prediction)

print('Efectividad', accuracy)

Efectividad 0.8879159369527145
